apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: jstc348c4-nodejs
  janus-idp.io/tekton: jstc348c4-nodejs
  backstage.io/kubernetes-id: jstc348c4-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: jstc348c4-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
